const prompts = [
  "Just had",
  "Can't believe I",
  "Feeling amazing after",
  "Loving",
  "Excited about",
  "Celebrating",
  "Enjoying",
  "Hanging out at",
  "Finally got to",
  "So happy to have",
  "Nothing beats",
  "Can't get enough of",
  "Missing",
  "Dreaming of",
  "Thinking about",
  "Spending time at",
  "Making the most of",
  "Looking forward to",
  "Chilling at",
  "Going on a trip to",
  "Trying out",
  "Getting ready for",
  "Starting my day with",
  "Working hard at",
  "Relaxing with",
  "Trying something new at",
  "Just got back from",
  "Staying productive with",
  "Finding joy in",
  "Exploring",
];

const places = [
  "the park",
  "the beach",
  "a fancy restaurant",
  "my favorite coffee shop",
  "a cozy bookshop",
  "the gym",
  "the movie theater",
  "a rooftop bar",
  "a new city",
  "a secluded cabin",
  "a crowded festival",
  "the art museum",
  "a yoga studio",
  "the library",
  "the amusement park",
  "the arcade",
  "the dance club",
  "a music concert",
  "the airport",
  "a snowy mountain",
  "a sunny beach",
  "the shopping mall",
  "a historic site",
  "the aquarium",
  "a sports stadium",
  "a nature reserve",
  "a local bar",
  "the city streets",
  "a cozy fireplace",
  "the countryside",
];

const activities = [
  "reading a book",
  "going for a run",
  "watching a movie",
  "painting a picture",
  "playing a game",
  "cooking dinner",
  "having a picnic",
  "baking cookies",
  "dancing",
  "listening to music",
  "meditating",
  "doing yoga",
  "spending time with family",
  "hanging out with friends",
  "traveling",
  "exploring nature",
  "learning a new skill",
  "trying new food",
  "volunteering",
  "solving puzzles",
  "working out",
  "singing karaoke",
  "watching the sunset",
  "stargazing",
  "shopping",
  "attending a concert",
  "doing crafts",
  "taking a nap",
  "going on a date",
];

const people = [
  "my best friend",
  "my partner",
  "my family",
  "my coworkers",
  "my roommate",
  "my pet",
  "my neighbor",
  "my teacher",
  "my mentor",
  "my boss",
  "my coach",
  "my client",
  "my fan",
  "my follower",
  "my colleague",
  "my crush",
  "my ex",
  "my enemy",
  "my celebrity idol",
  "my random stranger",
];

const hashtags = [
  "#friends",
  "#goodtimes",
  "#love",
  "#instagood",
  "#photooftheday",
  "#fashion",
  "#beautiful",
  "#happy",
  "#cute",
  "#tbt",
  "#like4like",
  "#followme",
  "#picoftheday",
  "#follow",
  "#me",
  "#selfie",
  "#summer",
  "#art",
  "#instadaily",
  "#food",
  "#girl",
  "#style",
  "#smile",
  "#fun",
  "#life",
  "#family",
  "#nature",
  "#travel",
  "#fitness",
  "#beauty",
  "#music",
  "#sun",
  "#model",
  "#foodporn",
  "#motivation",
  "#girls",
  "#nofilter",
  "#pretty",
  "#photography",
  "#party",
  "#cool",
  "#baby",
  "#ootd",
  "#lifestyle",
  "#design",
  "#fashionista",
  "#workout",
  "#hair",
  "#dog",
  "#sunset",
  "#blessed",
  "#quotes"
];


const generatePost = (): string => {
  const prompt = prompts[Math.floor(Math.random() * prompts.length)];
  const place = places[Math.floor(Math.random() * places.length)];
  const activity = activities[Math.floor(Math.random() * activities.length)];
  const person = people[Math.floor(Math.random() * people.length)];
  const hashtag = `${hashtags[Math.floor(Math.random() * hashtags.length)]} ${hashtags[Math.floor(Math.random() * hashtags.length)]} ${hashtags[Math.floor(Math.random() * hashtags.length)]}`
  
  return `${prompt} ${activity} with ${person} at ${place}! ${hashtag}`;
}

export default generatePost
